namespace: koonix
name: hysteria
version: 0.2.1
description: Collection of roles for setting up Hysteria.
repository: https://github.com/koonix/ansible-hysteria
issues:     https://github.com/koonix/ansible-hysteria/issues
authors: [ 'koonix <me@koonix.org>' ]
license: [ 'MIT' ]
readme: README.md
tags:
  - hysteria
