- name: Create dirs
  ansible.builtin.file:
    state: directory
    path: '{{ item.path }}'
    mode: '{{ item.mode | default("700") }}'
    owner: root
    group: root
  loop:
    - path: '{{ docker_dir }}'
    - path: '{{ config_file | ansible.builtin.dirname }}'

- name: Install docker templates
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: '{{ item.mode | default("644") }}'
    owner: root
    group: root
  loop:
    - src: docker-compose.yml.j2
      dest: '{{ docker_dir }}/docker-compose.yml'

- name: Install config files
  ansible.builtin.copy:
    content: '{{ item.content }}'
    dest: '{{ item.dest }}'
    mode: '{{ item.mode | default("644") }}'
    owner: root
    group: root
  loop:
    - content: '{{ hysteria_client_config | ansible.builtin.to_json(indent=4, sort_keys=True) }}'
      dest: '{{ config_file }}'
  notify: hysteria_client_changed

- name: Remove extraneous files from docker dir
  ansible.builtin.shell:
    chdir: '{{ dir }}'
    cmd: |
      for file in * .*; do
        [ ! -e "$file" ] && continue
        case $file in
          {{ ( [ '.', '..' ] + keep ) | map('ansible.builtin.quote') | join('|') }}) ;;
          *) rm -r -- "$file"; echo removed ;;
        esac
      done
  register: rmextra
  changed_when: "'removed' in rmextra.stdout"
  vars:
    # IMPORTANT: update the 'keep' list to reflect the files that we want to keep
    dir: '{{ docker_dir }}'
    keep:
      - docker-compose.yml

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Start Hysteria
  ansible.builtin.command:
    argv: [ docker, compose, up, --detach, --remove-orphans ]
    chdir: '{{ docker_dir }}'
  register: compose
  changed_when: '"Started" in compose.stderr'
