- name: Remove extraneous Hysteria instances
  ansible.builtin.shell:
    chdir: '{{ dir }}'
    cmd: |
      for file in * .*; do
        [ ! -e "$file" ] && continue
        case $file in
          {{ ( [ '.', '..' ] + keep ) | map('ansible.builtin.quote') | join('|') }}) ;;
          *)
            if [ -e "$file/docker-compose.yml" ]; then
              docker compose --project-directory "$file" down
            fi
            rm -r -- "$file"
            echo removed
          ;;
        esac
      done
  register: rmextra
  changed_when: "'removed' in rmextra.stdout"
  vars:
    # IMPORTANT: update the 'keep' list to reflect the files that we want to keep
    dir: '{{ hysteria_lib_dir }}'
    keep: '{{ hysteria_instances | map(attribute="name") }}'

- name: Setup Hysteria instances
  ansible.builtin.include_tasks:
    file: setup.yml
  vars:
    instance_dir: '{{ hysteria_lib_dir }}/{{ instance.name }}'
  loop: '{{ hysteria_instances }}'
  loop_control:
    loop_var: instance
