dependency:
  name: galaxy
  options:
    requirements-file: molecule/requirements.yml

driver:
  name: vagrant
  provider:
    name: libvirt

platforms:
  - name: molecule-koonix-hysteria
    box: debian/bookworm64
